package bancho

import "fmt"

const (
	SERVER_USER_ID                     PacketID = 5
	SERVER_SEND_MESSAGE                         = 7
	SERVER_PONG                                 = 8
	SERVER_HANDLE_IRC_CHANGE_USERNAME           = 9
	SERVER_HANDLE_IRC_QUIT                      = 10
	SERVER_USER_STATS                           = 11
	SERVER_USER_LOGOUT                          = 12
	SERVER_SPECTATOR_JOINED                     = 13
	SERVER_SPECTATOR_LEFT                       = 14
	SERVER_SPECTATE_FRAMES                      = 15
	SERVER_VERSION_UPDATE                       = 19
	SERVER_SPECTATOR_CANT_SPECTATE              = 22
	SERVER_GET_ATTENTION                        = 23
	SERVER_NOTIFICATION                         = 24
	SERVER_UPDATE_MATCH                         = 26
	SERVER_NEW_MATCH                            = 27
	SERVER_DISPOSE_MATCH                        = 28
	SERVER_TOGGLE_BLOCK_NON_FRIEND_DMS          = 34
	SERVER_MATCH_JOIN_SUCCESS                   = 36
	SERVER_MATCH_JOIN_FAIL                      = 37
	SERVER_FELLOW_SPECTATOR_JOINED              = 42
	SERVER_FELLOW_SPECTATOR_LEFT                = 43
	SERVER_ALL_PLAYERS_LOADED                   = 45
	SERVER_MATCH_START                          = 46
	SERVER_MATCH_SCORE_UPDATE                   = 48
	SERVER_MATCH_TRANSFER_HOST                  = 50
	SERVER_MATCH_ALL_PLAYERS_LOADED             = 53
	SERVER_MATCH_PLAYER_FAILED                  = 57
	SERVER_MATCH_COMPLETE                       = 58
	SERVER_MATCH_SKIP                           = 61
	SERVER_UNAUTHORIZED                         = 62
	SERVER_CHANNEL_JOIN_SUCCESS                 = 64
	SERVER_CHANNEL_INFO                         = 65
	SERVER_CHANNEL_KICK                         = 66
	SERVER_CHANNEL_AUTO_JOIN                    = 67
	SERVER_BEATMAP_INFO_REPLY                   = 69
	SERVER_PRIVILEGES                           = 71
	SERVER_FRIENDS_LIST                         = 72
	SERVER_PROTOCOL_VERSION                     = 75
	SERVER_MAIN_MENU_ICON                       = 76
	SERVER_MONITOR                              = 80
	SERVER_MATCH_PLAYER_SKIPPED                 = 81
	SERVER_USER_PRESENCE                        = 83
	SERVER_RESTART                              = 86
	SERVER_MATCH_INVITE                         = 88
	SERVER_CHANNEL_INFO_END                     = 89
	SERVER_MATCH_CHANGE_PASSWORD                = 91
	SERVER_SILENCE_END                          = 92
	SERVER_USER_SILENCED                        = 94
	SERVER_USER_PRESENCE_SINGLE                 = 95
	SERVER_USER_PRESENCE_BUNDLE                 = 96
	SERVER_USER_DM_BLOCKED                      = 100
	SERVER_TARGET_IS_SILENCED                   = 101
	SERVER_VERSION_UPDATE_FORCED                = 102
	SERVER_SWITCH_SERVER                        = 103
	SERVER_ACCOUNT_RESTRICTED                   = 104
	SERVER_RTX                                  = 105
	SERVER_MATCH_ABORT                          = 106
	SERVER_SWITCH_TOURNAMENT_SERVER             = 107

	CLIENT_CHANGE_ACTION                  = 0
	CLIENT_SEND_PUBLIC_MESSAGE            = 1
	CLIENT_LOGOUT                         = 2
	CLIENT_REQUEST_STATUS_UPDATE          = 3
	CLIENT_PING                           = 4
	CLIENT_START_SPECTATING               = 16
	CLIENT_STOP_SPECTATING                = 17
	CLIENT_SPECTATE_FRAMES                = 18
	CLIENT_ERROR_REPORT                   = 20
	CLIENT_CANT_SPECTATE                  = 21
	CLIENT_SEND_PRIVATE_MESSAGE           = 25
	CLIENT_PART_LOBBY                     = 29
	CLIENT_JOIN_LOBBY                     = 30
	CLIENT_CREATE_MATCH                   = 31
	CLIENT_JOIN_MATCH                     = 32
	CLIENT_PART_MATCH                     = 33
	CLIENT_MATCH_CHANGE_SLOT              = 38
	CLIENT_MATCH_READY                    = 39
	CLIENT_MATCH_LOCK                     = 40
	CLIENT_MATCH_CHANGE_SETTINGS          = 41
	CLIENT_MATCH_START                    = 44
	CLIENT_MATCH_SCORE_UPDATE             = 47
	CLIENT_MATCH_COMPLETE                 = 49
	CLIENT_MATCH_CHANGE_MODS              = 51
	CLIENT_MATCH_LOAD_COMPLETE            = 52
	CLIENT_MATCH_NO_BEATMAP               = 54
	CLIENT_MATCH_NOT_READY                = 55
	CLIENT_MATCH_FAILED                   = 56
	CLIENT_MATCH_HAS_BEATMAP              = 59
	CLIENT_MATCH_SKIP_REQUEST             = 60
	CLIENT_CHANNEL_JOIN                   = 63
	CLIENT_BEATMAP_INFO_REQUEST           = 68
	CLIENT_MATCH_TRANSFER_HOST            = 70
	CLIENT_FRIEND_ADD                     = 73
	CLIENT_FRIEND_REMOVE                  = 74
	CLIENT_MATCH_CHANGE_TEAM              = 77
	CLIENT_CHANNEL_PART                   = 78
	CLIENT_RECEIVE_UPDATES                = 79
	CLIENT_SET_AWAY_MESSAGE               = 82
	CLIENT_IRC_ONLY                       = 84
	CLIENT_USER_STATS_REQUEST             = 85
	CLIENT_MATCH_INVITE                   = 87
	CLIENT_MATCH_CHANGE_PASSWORD          = 90
	CLIENT_TOURNAMENT_MATCH_INFO_REQUEST  = 93
	CLIENT_USER_PRESENCE_REQUEST          = 97
	CLIENT_USER_PRESENCE_REQUEST_ALL      = 98
	CLIENT_TOGGLE_BLOCK_NON_FRIEND_DMS    = 99
	CLIENT_TOURNAMENT_JOIN_MATCH_CHANNEL  = 108
	CLIENT_TOURNAMENT_LEAVE_MATCH_CHANNEL = 109
)

func (p PacketID) String() string {
	switch p {
	case SERVER_USER_ID:
		return "SERVER_USER_ID"
	case SERVER_SEND_MESSAGE:
		return "SERVER_SEND_MESSAGE"
	case SERVER_PONG:
		return "SERVER_PONG"
	case SERVER_HANDLE_IRC_CHANGE_USERNAME:
		return "SERVER_HANDLE_IRC_CHANGE_USERNAME"
	case SERVER_HANDLE_IRC_QUIT:
		return "SERVER_HANDLE_IRC_QUIT"
	case SERVER_USER_STATS:
		return "SERVER_USER_STATS"
	case SERVER_USER_LOGOUT:
		return "SERVER_USER_LOGOUT"
	case SERVER_SPECTATOR_JOINED:
		return "SERVER_SPECTATOR_JOINED"
	case SERVER_SPECTATOR_LEFT:
		return "SERVER_SPECTATOR_LEFT"
	case SERVER_SPECTATE_FRAMES:
		return "SERVER_SPECTATE_FRAMES"
	case SERVER_VERSION_UPDATE:
		return "SERVER_VERSION_UPDATE"
	case SERVER_SPECTATOR_CANT_SPECTATE:
		return "SERVER_SPECTATOR_CANT_SPECTATE"
	case SERVER_GET_ATTENTION:
		return "SERVER_GET_ATTENTION"
	case SERVER_NOTIFICATION:
		return "SERVER_NOTIFICATION"
	case SERVER_UPDATE_MATCH:
		return "SERVER_UPDATE_MATCH"
	case SERVER_NEW_MATCH:
		return "SERVER_NEW_MATCH"
	case SERVER_DISPOSE_MATCH:
		return "SERVER_DISPOSE_MATCH"
	case SERVER_TOGGLE_BLOCK_NON_FRIEND_DMS:
		return "SERVER_TOGGLE_BLOCK_NON_FRIEND_DMS"
	case SERVER_MATCH_JOIN_SUCCESS:
		return "SERVER_MATCH_JOIN_SUCCESS"
	case SERVER_MATCH_JOIN_FAIL:
		return "SERVER_MATCH_JOIN_FAIL"
	case SERVER_FELLOW_SPECTATOR_JOINED:
		return "SERVER_FELLOW_SPECTATOR_JOINED"
	case SERVER_FELLOW_SPECTATOR_LEFT:
		return "SERVER_FELLOW_SPECTATOR_LEFT"
	case SERVER_ALL_PLAYERS_LOADED:
		return "SERVER_ALL_PLAYERS_LOADED"
	case SERVER_MATCH_START:
		return "SERVER_MATCH_START"
	case SERVER_MATCH_SCORE_UPDATE:
		return "SERVER_MATCH_SCORE_UPDATE"
	case SERVER_MATCH_TRANSFER_HOST:
		return "SERVER_MATCH_TRANSFER_HOST"
	case SERVER_MATCH_ALL_PLAYERS_LOADED:
		return "SERVER_MATCH_ALL_PLAYERS_LOADED"
	case SERVER_MATCH_PLAYER_FAILED:
		return "SERVER_MATCH_PLAYER_FAILED"
	case SERVER_MATCH_COMPLETE:
		return "SERVER_MATCH_COMPLETE"
	case SERVER_MATCH_SKIP:
		return "SERVER_MATCH_SKIP"
	case SERVER_UNAUTHORIZED:
		return "SERVER_UNAUTHORIZED"
	case SERVER_CHANNEL_JOIN_SUCCESS:
		return "SERVER_CHANNEL_JOIN_SUCCESS"
	case SERVER_CHANNEL_INFO:
		return "SERVER_CHANNEL_INFO"
	case SERVER_CHANNEL_KICK:
		return "SERVER_CHANNEL_KICK"
	case SERVER_CHANNEL_AUTO_JOIN:
		return "SERVER_CHANNEL_AUTO_JOIN"
	case SERVER_BEATMAP_INFO_REPLY:
		return "SERVER_BEATMAP_INFO_REPLY"
	case SERVER_PRIVILEGES:
		return "SERVER_PRIVILEGES"
	case SERVER_FRIENDS_LIST:
		return "SERVER_FRIENDS_LIST"
	case SERVER_PROTOCOL_VERSION:
		return "SERVER_PROTOCOL_VERSION"
	case SERVER_MAIN_MENU_ICON:
		return "SERVER_MAIN_MENU_ICON"
	case SERVER_MONITOR:
		return "SERVER_MONITOR"
	case SERVER_MATCH_PLAYER_SKIPPED:
		return "SERVER_MATCH_PLAYER_SKIPPED"
	case SERVER_USER_PRESENCE:
		return "SERVER_USER_PRESENCE"
	case SERVER_RESTART:
		return "SERVER_RESTART"
	case SERVER_MATCH_INVITE:
		return "SERVER_MATCH_INVITE"
	case SERVER_CHANNEL_INFO_END:
		return "SERVER_CHANNEL_INFO_END"
	case SERVER_MATCH_CHANGE_PASSWORD:
		return "SERVER_MATCH_CHANGE_PASSWORD"
	case SERVER_SILENCE_END:
		return "SERVER_SILENCE_END"
	case SERVER_USER_SILENCED:
		return "SERVER_USER_SILENCED"
	case SERVER_USER_PRESENCE_SINGLE:
		return "SERVER_USER_PRESENCE_SINGLE"
	case SERVER_USER_PRESENCE_BUNDLE:
		return "SERVER_USER_PRESENCE_BUNDLE"
	case SERVER_USER_DM_BLOCKED:
		return "SERVER_USER_DM_BLOCKED"
	case SERVER_TARGET_IS_SILENCED:
		return "SERVER_TARGET_IS_SILENCED"
	case SERVER_VERSION_UPDATE_FORCED:
		return "SERVER_VERSION_UPDATE_FORCED"
	case SERVER_SWITCH_SERVER:
		return "SERVER_SWITCH_SERVER"
	case SERVER_ACCOUNT_RESTRICTED:
		return "SERVER_ACCOUNT_RESTRICTED"
	case SERVER_RTX:
		return "SERVER_RTX"
	case SERVER_MATCH_ABORT:
		return "SERVER_MATCH_ABORT"
	case SERVER_SWITCH_TOURNAMENT_SERVER:
		return "SERVER_SWITCH_TOURNAMENT_SERVER"

	case CLIENT_CHANGE_ACTION:
		return "CLIENT_CHANGE_ACTION"
	case CLIENT_SEND_PUBLIC_MESSAGE:
		return "CLIENT_SEND_PUBLIC_MESSAGE"
	case CLIENT_LOGOUT:
		return "CLIENT_LOGOUT"
	case CLIENT_REQUEST_STATUS_UPDATE:
		return "CLIENT_REQUEST_STATUS_UPDATE"
	case CLIENT_PING:
		return "CLIENT_PING"
	case CLIENT_START_SPECTATING:
		return "CLIENT_START_SPECTATING"
	case CLIENT_STOP_SPECTATING:
		return "CLIENT_STOP_SPECTATING"
	case CLIENT_SPECTATE_FRAMES:
		return "CLIENT_SPECTATE_FRAMES"
	case CLIENT_ERROR_REPORT:
		return "CLIENT_ERROR_REPORT"
	case CLIENT_CANT_SPECTATE:
		return "CLIENT_CANT_SPECTATE"
	case CLIENT_SEND_PRIVATE_MESSAGE:
		return "CLIENT_SEND_PRIVATE_MESSAGE"
	case CLIENT_PART_LOBBY:
		return "CLIENT_PART_LOBBY"
	case CLIENT_JOIN_LOBBY:
		return "CLIENT_JOIN_LOBBY"
	case CLIENT_CREATE_MATCH:
		return "CLIENT_CREATE_MATCH"
	case CLIENT_JOIN_MATCH:
		return "CLIENT_JOIN_MATCH"
	case CLIENT_PART_MATCH:
		return "CLIENT_PART_MATCH"
	case CLIENT_MATCH_CHANGE_SLOT:
		return "CLIENT_MATCH_CHANGE_SLOT"
	case CLIENT_MATCH_READY:
		return "CLIENT_MATCH_READY"
	case CLIENT_MATCH_LOCK:
		return "CLIENT_MATCH_LOCK"
	case CLIENT_MATCH_CHANGE_SETTINGS:
		return "CLIENT_MATCH_CHANGE_SETTINGS"
	case CLIENT_MATCH_START:
		return "CLIENT_MATCH_START"
	case CLIENT_MATCH_SCORE_UPDATE:
		return "CLIENT_MATCH_SCORE_UPDATE"
	case CLIENT_MATCH_COMPLETE:
		return "CLIENT_MATCH_COMPLETE"
	case CLIENT_MATCH_CHANGE_MODS:
		return "CLIENT_MATCH_CHANGE_MODS"
	case CLIENT_MATCH_LOAD_COMPLETE:
		return "CLIENT_MATCH_LOAD_COMPLETE"
	case CLIENT_MATCH_NO_BEATMAP:
		return "CLIENT_MATCH_NO_BEATMAP"
	case CLIENT_MATCH_NOT_READY:
		return "CLIENT_MATCH_NOT_READY"
	case CLIENT_MATCH_FAILED:
		return "CLIENT_MATCH_FAILED"
	case CLIENT_MATCH_HAS_BEATMAP:
		return "CLIENT_MATCH_HAS_BEATMAP"
	case CLIENT_MATCH_SKIP_REQUEST:
		return "CLIENT_MATCH_SKIP_REQUEST"
	case CLIENT_CHANNEL_JOIN:
		return "CLIENT_CHANNEL_JOIN"
	case CLIENT_BEATMAP_INFO_REQUEST:
		return "CLIENT_BEATMAP_INFO_REQUEST"
	case CLIENT_MATCH_TRANSFER_HOST:
		return "CLIENT_MATCH_TRANSFER_HOST"
	case CLIENT_FRIEND_ADD:
		return "CLIENT_FRIEND_ADD"
	case CLIENT_FRIEND_REMOVE:
		return "CLIENT_FRIEND_REMOVE"
	case CLIENT_MATCH_CHANGE_TEAM:
		return "CLIENT_MATCH_CHANGE_TEAM"
	case CLIENT_CHANNEL_PART:
		return "CLIENT_CHANNEL_PART"
	case CLIENT_RECEIVE_UPDATES:
		return "CLIENT_RECEIVE_UPDATES"
	case CLIENT_SET_AWAY_MESSAGE:
		return "CLIENT_SET_AWAY_MESSAGE"
	case CLIENT_IRC_ONLY:
		return "CLIENT_IRC_ONLY"
	case CLIENT_USER_STATS_REQUEST:
		return "CLIENT_USER_STATS_REQUEST"
	case CLIENT_MATCH_INVITE:
		return "CLIENT_MATCH_INVITE"
	case CLIENT_MATCH_CHANGE_PASSWORD:
		return "CLIENT_MATCH_CHANGE_PASSWORD"
	case CLIENT_TOURNAMENT_MATCH_INFO_REQUEST:
		return "CLIENT_TOURNAMENT_MATCH_INFO_REQUEST"
	case CLIENT_USER_PRESENCE_REQUEST:
		return "CLIENT_USER_PRESENCE_REQUEST"
	case CLIENT_USER_PRESENCE_REQUEST_ALL:
		return "CLIENT_USER_PRESENCE_REQUEST_ALL"
	case CLIENT_TOGGLE_BLOCK_NON_FRIEND_DMS:
		return "CLIENT_TOGGLE_BLOCK_NON_FRIEND_DMS"
	case CLIENT_TOURNAMENT_JOIN_MATCH_CHANNEL:
		return "CLIENT_TOURNAMENT_JOIN_MATCH_CHANNEL"
	case CLIENT_TOURNAMENT_LEAVE_MATCH_CHANNEL:
		return "CLIENT_TOURNAMENT_LEAVE_MATCH_CHANNEL"
	default:
		return fmt.Sprintf("UNKNOWN (%d)", uint16(p))
	}
}
